# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    api.client_id: '6a8519ef6de3412490ec149fdf702de1'
    api.secret: 'e804ce5fe1f44bb08eb37a738dc9bfe5'

services:
   service_api:
        class: AppBundle\Service\Api 
        calls:
            - [setClientId, ['%api.client_id%']]
            - [setSecret, ['%api.secret%']]